# Generated by Django 5.1.3 on 2024-11-16 11:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubVariants',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'sub variant',
                'verbose_name_plural': 'sub variants',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('-created_at', 'ProductID'), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='CreatedDate',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='UpdatedDate',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='CreatedDate',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='UpdatedDate',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='products',
            name='Description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='Price',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='ProductCode',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=20, null=True)),
                ('refrence_number', models.CharField(blank=True, max_length=200, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_product', to='products.subvariants')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.products')),
            ],
            options={
                'verbose_name': 'variant',
                'verbose_name_plural': 'variants',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='subvariants',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subvariants', to='products.variants'),
        ),
    ]
