# Generated by Django 5.1.3 on 2024-11-16 13:13

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_subvariants_alter_products_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ProductImage',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
