# Generated by Django 5.1.3 on 2024-11-17 05:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Active',
            new_name='IsActive',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='variant',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='subvariants',
            unique_together={('variant', 'option_name')},
        ),
        migrations.AlterUniqueTogether(
            name='variants',
            unique_together={('product', 'name')},
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=20, null=True)),
                ('sub_variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.subvariants')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='products.stock'),
        ),
    ]
